### PR TITLE
add hook to make sure README.Rmd hasn't been edited more recently than README.md

### PR DESCRIPTION
**Pull request by bfgray3**
Adapted from the [hook](https://github.com/r-lib/usethis/blob/master/inst/templates/readme-rmd-pre-commit.sh) from usethis.  I don't love the name `check-readme-rmd-rendered`; let me know if you have a better idea.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Thanks. I think to make this a bit more pre-commit like, we should make also use of the mechanism provided for file selection. See for example see the `yml`  for the styler hook. This will also make it a bit faster since the hook won't be run when no README is staged. Also:

- Can we be more informative in the case of an error? 
- Does this work on all platforms?

**Comment by bfgray3** [comment]
I'm not sure if this will work on Windows.  I'm not an expert on these things, but maybe it will just work on platforms that have `/bin/bash`.  If the shebang for the documenting and styling hooks works on a given system then I would bet this one would, but I don't do much programming on Windows and like I mentioned, I'm not an expert at this stuff.

**Comment by lorenzwalthert** [comment]
Ok. Can you fix the merge conflict with the README? Well let's see if we get someone to test this locally on Windows for now. I also don't have a windows machine currently. @jonmcalder would you consider running this test? 

One has to, for example: 

* clone this repo.
* install pre-commit as described [here](https://pre-commit.com/#intro).
* edit the README.Rmd and stage it.
* place `pre-commit-config.yaml` in the root that looks like this
 
```yaml
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: 2da9a80 
    hooks: 
    -   id: check-readme-rmd-rendered
```

And run `git commit`  and make sure it fails. Then knit the rmd to md, stage both and try again and then it should work.
in `.pre-commit-config.yaml` in a git repo

**Comment by lorenzwalthert** [comment]
Since `usethis:::render_template("readme-rmd-pre-commit.sh", "usethis")`  also has a shebang header with `/bin/bash` and does not mention os specific limitations, I think we can assume this to work on all platforms.

**Comment by lorenzwalthert** [comment]
I can't get this work. Can you? It seems pre-commit modifies the files at some place before the bash script gets executed. When I run `./bin/check-rmd-rendered-md`, everything is fine.

**Comment by lorenzwalthert** [comment]
Reference: https://github.com/pre-commit/pre-commit/issues/1080

**Comment by lorenzwalthert** [comment]
Ok, all fixed, see reference above.

**Comment by bfgray3** [comment]
Thanks!  I've been away from open source for a while but I appreciate your help.

**Pull request merged**
